version: '3.8'

services:
  app:
    build: .
    container_name: clutch-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/clutchdb

  mongo:
    image: mongo
    container_name: clutch-mongo
    ports:
      - "27017:27017"