version: "3.8"

services:
  mongo:
    image: mongo
    container_name: clutch-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  clutch-app:
    build: .
    container_name: clutch-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  mongo-data: