version: '3'
services:
  mongo:
    image: mongo
    container_name: clutch-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: clutch-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo

volumes:
  mongo-data:
